### PR TITLE
Fix scroll to bottom widget

### LINKED ISSUE #30: scrollToBottom widget remains visible after leaving chat page
I am using package version 1.0.15 and it seems the problem is back. The scrollToBottom widget stays on top of everything even when I leave the chat screen.

This is the same problem that was brought up in issue: https://github.com/fayeed/dash_chat/issues/4

I am using:

dash_chat: ^1.0.15

Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (3 months ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0

From the .metadata file:

version:
revision: 27321ebbad34b0a3fafe99fac037102196d655ff
channel: stable

project_type: app

### PR DESCRIPTION
**Pull request by SebastienBtr**
fix #30 by using a Stack and introducing new properties to custom scroll to bottom widget

### CODE REVIEW

File: lib/src/chat_view.dart [hunk 1]
```diff
@@ -452,117 +422,144 @@ class DashChatState extends State<DashChat> {
...
+                        scrollController: widget.scrollController != null
+                            ? widget.scrollController
+                            : scrollController,
+                        focusNode: inputFocusNode,
+                        reverse: widget.inverted)
+                ],
+              ),
+              if (visible)
+                Positioned(
+                  right: 0,
```
Comment (fayeed) [inline lib/src/chat_view.dart:548]: Currently, this aligns the button to the center of the screen, so I was thinking a new property may be `scrollButtonAlignment` would be a good option, which will be an enum `left, right, center` like so.

File: lib/src/widgets/scroll_to_bottom.dart [hunk 2]
```diff
@@ -3,31 +3,40 @@ part of dash_chat;
...
+    this.backgroundColor,
+    this.textColor,
   });
 
   @override
   Widget build(BuildContext context) {
     return Container(
-      width: 48.0,
-      height: 48.0,
+      width: 35,
```
Comment (fayeed) [inline lib/src/widgets/scroll_to_bottom.dart:21]: Also, if we are providing `scrollToBottom` Button properties we can have dimensions property for setting the height & width of the button.

File: lib/src/chat_view.dart (hunk 1 above)
Comment (SebastienBtr) [reply lib/src/chat_view.dart:548]: I think that would be better to have a property to set the exact position, because the bottom position might not be enough if you add something as a footer or more margin/padding to the toolbar, do you think a Map<String, String> with the keys being `right`, `left`, `top`, `bottom` would be ok?

File: lib/src/widgets/scroll_to_bottom.dart (hunk 2 above)
Comment (SebastienBtr) [reply lib/src/widgets/scroll_to_bottom.dart:21]: Yes, we can add `height` and `width` to the map I mentioned below

File: lib/src/chat_view.dart (hunk 1 above)
Comment (fayeed) [reply lib/src/chat_view.dart:548]: Maybe A simple class `ScrollToBottomWidgetStyle` with property `backgroundColor, fillColor, height, width, left, right, bottom` would be better.

Comment (fayeed) [reply lib/src/chat_view.dart:548]: It would also help with making the package more modular.
